### ISSUE TITLE
Sort sections in sidebar better

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaPackageComparisons/JuliaPackageComparisons.github.io#22]
There are already a lot of sections, and it can be hard to keep an overview of the sidebar. A search functionality (mentioned in #3) would help a lot, but the sorting should be sorted out in any case.

Current sorting suggestions:
- Alphabetical (current sorting)
- By number of stargazers of packaged mentioned in section
- Grouping related domains into meta-domains

Or some combination of the above, e.g. sorting by stargazers but making an exception to put nonlinear and linear solver sections next to each other. Or sorting between meta-domains by stargazers, and within them alphabetically. It might also be nice to include the sum of stargazers of mentioned packages in the sidebar-entry, which could be combined by any of the sorting rules.

Or perhaps all of the above. I am no website wizard, but I believe it should be possible to change the sorting by a drop-down. As a band-aid fix, there could be a separate overview-page for each sorting that each contains all sections, but sorted by different rules. The user could then visit the overview-page with the sorting that they find the best.

Conciderations:
The page should be easy to get an overview of. Alphabetical is simple, and facilitates looking for specific domains. It does however run the risk of drowning domains that are important to many between domains that are only important to a few. This last problem is best tackled by stargazer-sorting. And then there is the issue of putting related domains next to each other, which is conceptually cleaner.

**Comment by hyrodium** [comment]
Here's a draft list of meta-domains for the current sections.

## Data structure
* [dataframes](https://juliapackagecomparisons.github.io/pages/dataframes)
* [graphs](https://juliapackagecomparisons.github.io/pages/graphs)

## Acceleration
* [loop_acceleration](https://juliapackagecomparisons.github.io/pages/loop_acceleration)
* [multithreading](https://juliapackagecomparisons.github.io/pages/multithreading)

## Math
* [differentiation](https://juliapackagecomparisons.github.io/pages/differentiation)
* [einsum](https://juliapackagecomparisons.github.io/pages/einsum)
* [linear_solvers](https://juliapackagecomparisons.github.io/pages/linear_solvers)
* [nonlinear_solvers](https://juliapackagecomparisons.github.io/pages/nonlinear_solvers)

## Machine Learning
* [machine_learning](https://juliapackagecomparisons.github.io/pages/machine_learning)
* [machine_learning_datasets](https://juliapackagecomparisons.github.io/pages/machine_learning_datasets)
* [neural_networks](https://juliapackagecomparisons.github.io/pages/neural_networks)

## Geometry
* [triangulations_or_tessellations](https://juliapackagecomparisons.github.io/pages/triangulations_or_tessellations)

## Graphics
* [plotting](https://juliapackagecomparisons.github.io/pages/plotting)

## Utils
* [piping](https://juliapackagecomparisons.github.io/pages/piping)
* [notebooks](https://juliapackagecomparisons.github.io/pages/notebooks)
* [redefinable_structs](https://juliapackagecomparisons.github.io/pages/redefinable_structs)

## Interoperability
* [interoperability](https://juliapackagecomparisons.github.io/pages/interoperability)

## Web
* [web_apps](https://juliapackagecomparisons.github.io/pages/web_apps)
* [static_websites](https://juliapackagecomparisons.github.io/pages/static_websites)

## Uncategorized yet..
* [control_systems](https://juliapackagecomparisons.github.io/pages/control_systems)
* [metrics](https://juliapackagecomparisons.github.io/pages/metrics)
* [probabilistic_programming](https://juliapackagecomparisons.github.io/pages/probabilistic_programming)
* [saving_files](https://juliapackagecomparisons.github.io/pages/saving_files)
* [signal_processing](https://juliapackagecomparisons.github.io/pages/signal_processing)
* [uncertainty_propagation](https://juliapackagecomparisons.github.io/pages/uncertainty_propagation)
* [units](https://juliapackagecomparisons.github.io/pages/units)

**Comment by KronosTheLate** [comment]
That is a good list! The current lost of pages is long and hard to get an overview of, so something like this would help out a ton. Do you know how to create items with subitems in the sidebar? I have to admit, I know nothing about CSS. But in reference to #6, we might want to change the overall theme to "just-the-docs" (as you know, because it was you suggestion), so it is possible that implementing this should wait until the theme is changed.

To be more conclusive: I love the sorting by meta-domains, and suggest we hold off on changing it until the sidebar is just the way we want it.

As a sidenote, all the names of different pages/domains are off the top of my head. If you see better page-names, that is "up for graps" so to speak.
