### ISSUE TITLE
Makie more popular than plots

### ISSUE THREAD

**Issue by behinger** [JuliaPackageComparisons/JuliaPackageComparisons.github.io#23]
Hi! Great Project, already found a useful package!!

Minor point: Makie has now 2.1k Stars, Plots only 1.8k
In the section it currently says Plots is more popular than Makie.

If you agree, I could do a minor edit on the section.
Best, Benedikt

**Comment by KronosTheLate** [comment]
Hey! My thinking is the same. The current content is just an outdated copy of a comment chris racakas made on discourse.

In fact, I have been brewing on thoughts for a complete rewrite. A rough outline is something like:

Intro:
Say that we will split plotting packages into general purpose, specific styles (grammar of graphics, and other styles if others exist), and specific domains like maps, brain-scan data and stuff like that. 

General plotting packages:
Compare Makie, Plots, and potentially other general purpose packages. General jist is that Plots is the fastest option to get you most of the way there, and enjoys good integration via recipes. Makie is a little more verbose, and is heavier (longer precompilation), but is one of the most flexible and custumizable plotting systems of any programming language (I am not 100% sure about that, but I think it is true).

Grammar og graphics:
Vega and Vegalite, ggplot wrappers, AlgebraOfGraphics, perhaps more

Specific domains:
I would need to research more what goes here



If you agree with that jist, or have other thoughs and viewpoints, I would love input and help. I think it will be really important to get the comparison of plotting packages right, as it is one domain in which we have all struggled with choosing the right package.

**Comment by behinger** [comment]
hey, sounds very reasonable to me.

## Some things to add:

Should we highlight the actual plotting packages that are summarized in Plots.jl (https://docs.juliaplots.org/latest/backends/)? Some for sure have good standalone applications, e.g. UnicodePlots.jl

## Specific Domains
Did you think about UnicodePlots.jl here? or specific things like e.g. PlutoPlotly.jl?

**Comment by KronosTheLate** [comment]
Thanks for tour thoughts! Good points.

> Should we highlight the actual plotting packages that are summarized in Plots.jl

I am not sure! Do people use them alone? Is such use reccomended or ecpected by developers? I guess some do, and those deserve a standalone mention.

> Did you think about UnicodePlots.jl here? 

I forgot it as I was writing the comment, but terminal plotting is worthy of a subsection. UnicodePlots, Sixel based plotting, and KittyTerminalImages deserve some comparisons.

As for PlotyPlotly, I am not sure in which catogery that would go. Perhaps there needs to be a "misc" subsection.

**Comment by KronosTheLate** [comment]
I fixed the worst wording in [this](https://github.com/JuliaPackageComparisons/JuliaPackageComparisons.github.io/commit/aded5015af37dfee81b3c18d656c31529d818923) PR, and created #25. With that, I think we can close this issue.
