### ISSUE TITLE
Automatically pull the github stars and last update date

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaPackageComparisons/JuliaPackageComparisons.github.io#4]
This would greatly help asses the activity and populatity of packages, but manually adding it is too much work.

**Comment by KronosTheLate** [comment]
I found something that may be really helpful:
```julia
julia> using GitHub

julia> GitHub.repo("JuliaPackageComparisons/JuliaPackageComparisons.github.io").stargazers_count
8
```

Perhaps the best solution would be to create a file mapping repo name to stars (updated with every site-build), and interpolate from the dictionary in the markdown files.

**Comment by KronosTheLate** [comment]
See https://franklinjl.org/syntax/markdown/#inserting_markdown. So we could use a julia script to write a markdown file for each package that would contain the stargazers and update time. Perhaps in a table at the start of each section?

A downstream effect I want is that the section menu should be sorted by a) the sum og stargazers for mentioned packages, or b) the maximum number of stargazers for the mentioned packages. Both metrics should correspond to the importance of the domain.

**Comment by DanielVandH** [comment]
Note that for unauthenticated requests like `GitHub.repo("JuliaPackageComparisons/JuliaPackageComparisons.github.io").stargazers_count`, you'll hit the rate limit (60) pretty quick, so be sure you provide an authentication key according to https://github.com/JuliaWeb/GitHub.jl#authentication.

**Comment by KronosTheLate** [comment]
Fantastic info, thank you for it! Do you agree with my proposed implementation, or do you know of better ways?

**Comment by DanielVandH** [comment]
It might be better if you (programmatically, of course, using `GitHub.jl`) just create a text table (or even just a DataFrame, as long as you can load it into Julia in Franklin from different files) storing information for each package, e.g.

Package Stars UpdateTime
X.jl         Y       A/B/C
...

rather than a markdown file for each package. That'll probably be more useful for your planned downstream effect that you mention.

**Comment by KronosTheLate** [comment]
Is it possible to interpolate such content into markdown? I want the data inside the text. 

The reason I suggested generating seperate markdown files is because it is the only way I know of to insert "variable" content such as stars into text. I am not about the format, but I imagine 2 possible uses:
1) Packages get subtitles on the page. These subtitles contain the number of stars
2) Section could start with a table with such data about the packages to be compared 

I do now know how to achieve these if the generated file is a text file containing the data about all packages mentioned in all sections.

**Comment by DanielVandH** [comment]
Ah. I think I see what you mean. What I had in mind was something like 

```julia
using JSON3, Dates, StructTypes
package_names = ["A.jl", "B.jl", "C.jl", "D.jl"]
package_stars = [1, 2, 3, 4]
package_last_activity = Date.(["2023-09-23", "2023-09-24", "2023-09-25", "2023-09-26"], Ref(DateFormat("y-m-d")))

struct PackageInfo
    stars::Int
    last_activity::Date
end
StructTypes.StructType(::Type{PackageInfo}) = StructTypes.Struct()

dict = Dict(package_names .=> PackageInfo.(package_stars, package_last_activity))
json = JSON3.write(dict) |> JSON3.read

open("package_data.json", "w") do io
    JSON3.pretty(io, json)
end
```

which gives 

```json
{
    "C.jl": {
        "stars": 3,
        "last_activity": "2023-09-25"
    },
    "D.jl": {
        "stars": 4,
        "last_activity": "2023-09-26"
    },
    "A.jl": {
        "stars": 1,
        "last_activity": "2023-09-23"
    },
    "B.jl": {
        "stars": 2,
        "last_activity": "2023-09-24"
    }
}
```

which you could then use for putting into the documents. But I'm not sure how easy that is in Markdown, without formatting the Markdown after the fact which you could just as well do with your original approach. I was thinking something like writing the Markdown like (with better text :) )

```markdown
 PackageName
!!-PackageName-!!

PackageName has !!-Stars-!! stars, and was last updated on !!-LastActivity-!!.
```

so that a postprocessing function could then replace the markers `!!-[w]-!!` with the appropriate information from the JSON. But that's probably more work than your idea again.

**Comment by hyrodium** [comment]
I think adding the following badges is enough.

* [![GitHub Repo stars](https://img.shields.io/github/stars/hyrodium/BasicBSpline.jl?style=social)](https://github.com/hyrodium/BasicBSpline.jl)
* [![GitHub last commit (branch)](https://img.shields.io/github/last-commit/hyrodium/BasicBSpline.jl/main)](https://github.com/hyrodium/BasicBSpline.jl/commits/main/)
* [![BasicBSpline Downloads](https://shields.io/endpoint?url=https://pkgs.genieframework.com/api/v1/badge/BasicBSpline)](https://pkgs.genieframework.com?packages=BasicBSpline)

It would be nice to add the following badges too, but some repositories don't support these badges.

* [![Stable](https://img.shields.io/badge/docs-stable-blue.svg)](https://hyrodium.github.io/BasicBSpline.jl/stable)
* [![Dev](https://img.shields.io/badge/docs-dev-blue.svg)](https://hyrodium.github.io/BasicBSpline.jl/dev)
* [![Build Status](https://github.com/hyrodium/BasicBSpline.jl/workflows/CI/badge.svg)](https://github.com/hyrodium/BasicBSpline.jl/actions)
* [![Coverage](https://codecov.io/gh/hyrodium/BasicBSpline.jl/branch/main/graph/badge.svg)](https://codecov.io/gh/hyrodium/BasicBSpline.jl)

**Comment by KronosTheLate** [comment]
Uh yes, autogeneration of those badges would be ideal. Do we know that it is possible?

**Comment by hyrodium** [comment]
One concern is the GitHub's rate limit.

>If your GitHub badge errors, it might be because you hit GitHub's rate limits. You can increase Shields.io's rate limit by adding the Shields GitHub application using your GitHub account.

https://shields.io/badges/git-hub-last-commit-branch

We can try putting the badges, and reconsider the badge if we have some problems.😄
