### ISSUE TITLE
Add some CI to check PR

### ISSUE THREAD

**Issue by hyrodium** [JuliaPackageComparisons/JuliaPackageComparisons.github.io#56]
* Check if all commands in `Deploy.yml` don't throw errors.
* Provide some preview pages. (maybe in another repository?)
* Spell check

x-ref: https://github.com/JuliaPackageComparisons/JuliaPackageComparisons.github.io/pull/55#issuecomment-1901776545

**Comment by hyrodium** [comment]
I tried to set up a GitHub action that generates preview pages on [my fork repository](https://github.com/hyrodium/JuliaPackageComparisons.github.io) and [a new repository for preview](https://github.com/hyrodium/JuliaPackageComparisonsPreview).

On this PR (https://github.com/hyrodium/JuliaPackageComparisons.github.io/pull/5), I succeeded in generating a preview documentation but there are still some problems.

* I'm not sure generating docs from a fork is technically possible.
  * e.g. Documenter.jl cannot deploy preview docs based on PR from a fork.
* The action should comment something like "The preview document is deployed here (link)", but I have not succeeded yet in my repos.

**Comment by KronosTheLate** [comment]
I think that there may only be a single GitHub-hosted page per organization/user. I therefore think that one will have to build locally to get previews of changes, unfortunately. So I think that getting previews on forks is not viable.

Better to make the instructions for building locally idiot-proof. Perhaps including how to clone a given fork and branch (`git clone -b branch_name https://github.com/username_of_forker/JuliaPackageComparisons.github.io`, for example `git clone -b just-the-docs https://github.com/hyrodium/JuliaPackageComparisons.github.io
`) would be a good idea.

**Comment by hyrodium** [comment]
Finally, I've succeeded in configuring the CI for preview :rocket::rocket::rocket:

## PRs that try deploying preview docs

* https://github.com/HyrodiumOrg/HyrodiumOrg.github.io/pull/12
* https://github.com/HyrodiumOrg/HyrodiumOrg.github.io/pull/13

## Repositories

* https://github.com/HyrodiumOrg/HyrodiumOrg.github.io
  * Original repository
  * I made an organization [HyrodiumOrg](https://github.com/HyrodiumOrg) to try the above PRs.
* https://github.com/HyrodiumOrg/preview
  * A repository to host preview docs
  * Preview docs should be hosted in this repository, not the original repository.
    * Preview docs are temporary and need cleanups. Separating git repositories makes cleanup easy.
    * We need to configure some additional permissions to deploy preview docs. Separating git repositories helps security improvements.
* https://github.com/hyrodium/HyrodiumOrg.github.io
  * Fork repository

## How that work

### PR from a fork repository

* A PR is made.
* A collaborator reviews in a security aspect, and labels 'ok to preview'.
* Preview job is triggered.
* Preview docs is deployed.
* A link to the preview docs is commented by github-actions bot.

### PR NOT from a fork repository

* A PR is made.
* Preview job is triggered.
* Preview docs is deployed.
* A link to the preview docs is commented by github-actions bot.

## Reference
* [Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
* [Try & Error log on the above PRs (Japanese, Franklin.jlでドキュメント生成でプレビューを有効化する)](https://zenn.dev/hyrodium/scraps/68e7d82389d14a)

---

@KronosTheLate 
* Could you try opening a dummy PR to https://github.com/HyrodiumOrg/HyrodiumOrg.github.io? That will help understand how `.github/workflows/Preview.yml` works.
* Could you invite me to JuliaPackageComarisons organization with some permissions? I need to:
  * Create a JuliaPackageComarisons/preview repository
  * Setup deploy & secret keys to push the preview
* Alternatively, you can set up the above configuration without inviting me to the organization. Feel free to ask me anything!

**Comment by KronosTheLate** [comment]
> Could you try opening a dummy PR to https://github.com/HyrodiumOrg/HyrodiumOrg.github.io? That will help understand how .github/workflows/Preview.yml works.

Done

> Could you invite me to the JuliaPackageComparisons organization with some permissions? I need to:

You have been invited to the JuliaPackageComparisons org with owner permissions. I hardly feel like there is any reason I should have more permission than you at this point ^_^

I am not fluent in GitHub, especially in automatic CI actions, deployment, etc. I was quite happy when I managed to create a GitHub hosted website xD So I am unable to keep up, but you have 100% thumbs up from me to do whatever you feel is beneficial. Your judgement has proven great so far :smile:

**Comment by hyrodium** [comment]
Thank you for the comment!
I really appreciate that you have founded this project, and I'm so happy to be part of it :blush: 

I will open a PR that enables preview CI after #65 is merged.
