### ISSUE TITLE
Show sidebar by default

### ISSUE THREAD

**Issue by mbauman** [JuliaPackageComparisons/JuliaPackageComparisons.github.io#6]
It'd be nice for the sidebar to just be a static element on all pages — it needn't be collapsable, I think

**Comment by KronosTheLate** [comment]
I would also like the github icon and optional theme that Documenter.jl provides. I could use some help with the css for that. I will likely also get to learning how to do it myself at some point, if nobody else steps up.

**Comment by hyrodium** [comment]
I think changing the theme is the shortcut for this. The "just-the-docs" theme shows the sidebar by default and hides the sidebar automatically when the page width is narrow. This theme is also adopted in [Franklin's main website](https://franklinjl.org/).
