### ISSUE TITLE
Move all contents to `docs` directory

### ISSUE THREAD

**Issue by hyrodium** [JuliaPackageComparisons/JuliaPackageComparisons.github.io#60]
`/CONTRIBUTING.md` file is not written for franklin docs, but the page is deployed at https://juliapackagecomparisons.github.io/CONTRIBUTING/.
This can be fixed by moving all Franklin-related filed to `docs` directory. The solution is the same as in Franklin.jl.

**Comment by KronosTheLate** [comment]
I am actually not sure what we want to do here - use the page you linked, or expect people to view in on github directly. I only knew about the second option, but the former looks pretty good. But currently we have both, which can be a source of confusion.

Am I right in thinking that you are suggesting we move "CONTRIBUTING.md" into a new directory "docs", in order to ensure that it **does not** deploy to the website? I think that sounds like a fine idea - The user will have to get into git and github to contribute anyways, and so it feels most natural to only keep the file viewable via github ^_^

**Comment by hyrodium** [comment]
>Am I right in thinking that you are suggesting we move "CONTRIBUTING.md" into a new directory "docs", in order to ensure that it does not deploy to the website?

No, if we move `CONTRIBUTING.md` to `docs/CONTRIBUTING.md`, the new confusing link will be https://juliapackagecomparisons.github.io/docs/CONTRIBUTING/.
Note that we don't have https://juliapackagecomparisons.github.io/README/ page despite of the `README.md` existence. This is because `IGNORE_FILES` is hardcoded in Franklin.jl.

https://github.com/tlienart/Franklin.jl/blob/8c043252f61e0a6217fd9c873a5be66cac5a8f3a/src/utils/paths.jl#L14-L15

**Comment by hyrodium** [comment]
The new directory structure I am planning is:

```
.
├── docs
|   ├── 404.md
|   ├── _assets
|   ├── config.md
|   ├── _css
|   ├── index.md
|   ├── _layout
|   ├── _libs
|   ├── LICENSE
|   ├── package.json
|   ├── package-lock.json
|   ├── pages
|   │   ├── agentbasedmodelling.md
|   │   ├── bspline.md
|   │   ├── control_systems.md
|   │   ├── dataframes.md
|   │   ├── differentiation.md
|   │   ├── einsum.md
|   │   ├── graphs.md
|   │   ├── interoperability.md
|   │   ├── linear_solvers.md
|   │   ├── loop_acceleration.md
|   │   ├── machine_learning_datasets.md
|   │   ├── machine_learning.md
|   │   ├── metrics.md
|   │   ├── multithreading.md
|   │   ├── neural_networks.md
|   │   ├── nonlinear_solvers.md
|   │   ├── notebooks.md
|   │   ├── piping.md
|   │   ├── plotting.md
|   │   ├── probabilistic_programming.md
|   │   ├── quaternions.md
|   │   ├── redefinable_structs.md
|   │   ├── saving_files.md
|   │   ├── signal_processing.md
|   │   ├── static_websites.md
|   │   ├── triangulations_or_tessellations.md
|   │   ├── uncertainty_propagation.md
|   │   ├── units.md
|   │   └── web_apps.md
|   ├── Project.toml
|   ├── _rss
|   │   ├── head.xml
|   │   └── item.xml
|   ├── search.md
|   └── utils.jl
├── logo (we can maintain logo graphics in this directory. (or maybe in other repo?))
├── CONTRIBUTING.md
└── README.md
```

**Comment by hyrodium** [comment]
Another possible solution is moving the contributing page to the Franklin-based website.
But this approach has the following disadvantages.

* We may have similar problems in the future.
* Keeping the root directory clean helps future contributors.

**Comment by KronosTheLate** [comment]
It sounds like you have thought this through rather well. I also like the thought of collecting everything into a folder, along with CONTRIBUTING and README. It feels cleaner. Feel free to implement the structure you have planned!
