### ISSUE TITLE
Put utility/types_compactification under acceleration section

### ISSUE THREAD

**Issue by Tortar** [JuliaPackageComparisons/JuliaPackageComparisons.github.io#85]
It is probably a better macro-section because (one of) the main point to use some of those packages is to avoid union-splitting

**Comment by KronosTheLate** [comment]
And perhaps rename "acceleration" to "performance enhancement" or "faster code" or something a little more clear?

**Comment by Tortar** [comment]
yes, "performance enhancement" seems better to me. Or maybe also "performance boosting"?

**Comment by KronosTheLate** [comment]
Something along those lines. There is more low-hanging fruit than this, but thanks for the issue. We will get to it at some point. If you would like to try your hand at making a PR yourself, you are most welcome to do so!
