### ISSUE TITLE
Broken badges is branchname != master, and custum badge inaccesible.

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaPackageComparisons/JuliaPackageComparisons.github.io#88]
The badges for last commit and codecov are broken for repos which do not use master as the default branch name.

The "custom badge" badge is also always "inaccessible" IDK what that means.

_Originally posted by @LilithHafner in https://github.com/JuliaPackageComparisons/JuliaPackageComparisons.github.io/pull/84#pullrequestreview-1946515199_
           
The issue is likely that all PkgSpec entries say "branch=master". The fix is to manually check each repo for what the default branch is. Alternatively, it should be possible to automate this, and not provide a branch.

**Comment by KronosTheLate** [comment]
The following should make it unnecessary to specify a branch:
```julia-repl
julia> GitHub.repo("JuliaPackageComparisons/JuliaPackageComparisons.github.io").default_branch
"main"
```

**Comment by KronosTheLate** [comment]
I feel like this might be a good time to propose an idea for reworking PkgInfo. My thinking is that we only really need the username and reponame, and from there we can run `GitHub.repo("$username/$reponame")` to get all the details, including the default branch and link to home page. The problem with this is that without authentication, one will run into a rate limit of 60 requests per hour. If one makes authenticated requests, one can have 5000 requests per hour, which should be plenty. I am not sure if we can provide an authentication token publicly, as I do not know how to prevent the holder from also being able to e.g. star repos. 

But perhaps it would be good enough to have one of us run the requests locally, updating a file with all package info, and pushing the update on a regular basis. As new users add PkgInfo entries, they can use the non-authentuicated requests to add new entries, as they do not need to make 60 requests per hour for that. Downside: manual update of repo data. Upside: simplify certain things, like default branch name and website link.

**Comment by LilithHafner** [comment]
I think that the github actions token in CI has the authenticated rate limit.

Re using only two strings to specify a source location: it would be nice to support non-github-hosted packages.

**Comment by KronosTheLate** [comment]
> Re using only two strings to specify a source location: it would be nice to support non-github-hosted packages.

Agreed. Though I am not sure how. It appears as if a lot can be queried via juliahub, which might provide a more uniform interface for all packages in the general registry, and make things hosting-platform agnostic. It would limit us to packages in the general registry, but I am good with that. 

Alternatively to JuliaHub always, would be a hosting-platform always solution. It could use a CI, triggered once a week, to update information about packages, using packages like Github.jl and GitLab.jl to support various hosting platforms. All we would need is the username, the repo name, and a hosting service (defaulting to GitHub) to query the data. The CI would update the data for one package at a time, and e.g. sleep for an hour once the rate limit is reached. In generating the page content, one would read the data from some file in the repo, as opposed querying web addresses, meaning that this once a week is the only time the CI server would query data.

As users add new PkgInfo's in their PRs, the data would be added by the user's computer locally, which would consume a different request allowance than the CI, which should ensure no conflicts.

**Comment by hyrodium** [comment]
> > The "custom badge" badge is also always "inaccessible" IDK what that means.
> 
> It is a badge for package download, but it has been broken since January 2024. See https://discourse.julialang.org/t/julia-downloads-stats-and-julia-downloads-badges/74712/7 for more information.

https://github.com/JuliaPackageComparisons/JuliaPackageComparisons.github.io/pull/84#issuecomment-2012382796

**Comment by hyrodium** [comment]
The badges were like this:

![image](https://github.com/JuliaPackageComparisons/JuliaPackageComparisons.github.io/assets/7488140/53345953-64ff-4b4d-9c92-9ba6cddc8eac)

https://github.com/JuliaPackageComparisons/JuliaPackageComparisons.github.io/pull/47#issuecomment-1891007333

**Comment by KronosTheLate** [comment]
> I think that the github actions token in CI has the authenticated rate limit.

I did not read this part of the comment properly, but that is really interesting! So how about this proposal:

We could write the GitHub.jl responses, of type `Repo`, to disk a file in this github repo, updating them daily with a CI, and use those for finding the link to documentation, branchname, and whatever else we want. Fieldnames of `Repo` are `(:name, :full_name, :description, :language, :default_branch, :owner, :parent, :source, :id, :size, :subscribers_count, :forks_count, :stargazers_count, :watchers_count, :open_issues_count, :url, :html_url, :clone_url, :ssh_url, :homepage, :pushed_at, :created_at, :updated_at, :has_issues, :has_wiki, :has_downloads, :has_pages, :license, :private, :fork, :permissions)`. If there is a Repo missing for a certain package, it could be queried using GitHub.jl, and added to the file. This should only happen a handful of times when adding new packages, meaning that it should run without problem for whoever is locally adding packages and testing the page. 

I have run a manual test with code in the new file `utils_manual.jl`, and fixed the branch name problem for now. But having it fixed automatically forever would also be nice.

**Comment by LilithHafner** [comment]
Polling all mentioned repos every day for changes in default branch (and ~20 other properties) seems like a bit much, but I suppose if you want to, then go for it. The only alternatives I can think of are manual.

**Comment by KronosTheLate** [comment]
I suppose that weekly would be almost as good, as a much smaller load. One of the things that we could get from a Repo object is also the stargazer count and the number of open issues, which help indicate how active a project is. Of course, seeing current number of issues without seeing the rate of new issues and how quicly they are closed might be misleading...

I will close this issue, and open a new one specifically for the custom badge.
